# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(related_name='friends', to='login_app.User'),
        ),
    ]
