# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20171025_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='users',
            new_name='buddies',
        ),
    ]
